#!/bin/bash
#
# install.sh — the real installer for the digital photo frame (v2).
#
# Run as root (bootstrap.sh does this for you):  sudo ./install.sh
#
# Idempotent and re-runnable: every step is safe to apply repeatedly, so later
# slices append their own install_* function + call without breaking re-runs.
# Targets a fresh Pi OS Lite flash (Bookworm).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# The frame user (owns the slideshow session). Defaults to the user who invoked
# sudo, then to 'mihai' (the PRD's provisioned user).
FRAME_USER="${FRAME_USER:-${SUDO_USER:-mihai}}"
FRAME_HOME=""   # resolved in require_user (keeps a clean error under set -e)

SHARE_DIR="/usr/local/share/slideshow"
FORCED_VIDEO_MODE="video=HDMI-A-1:1920x1080@60D"

require_root() {
  if [ "$(id -u)" -ne 0 ]; then
    echo "install: must run as root (use: sudo ./install.sh)" >&2
    exit 1
  fi
}

require_user() {
  # getent exits non-zero for an unknown user; capturing it in the `if`
  # condition keeps set -e/pipefail from aborting before we can complain.
  if ! FRAME_HOME="$(getent passwd "$FRAME_USER" | cut -d: -f6)" || [ -z "$FRAME_HOME" ]; then
    echo "install: user '$FRAME_USER' does not exist. Set FRAME_USER=<name>." >&2
    exit 1
  fi
  echo "install: target user = $FRAME_USER ($FRAME_HOME)"
}

# --- packages ---------------------------------------------------------------
install_packages() {
  echo "==> Installing packages (cage, feh, xwayland)"
  export DEBIAN_FRONTEND=noninteractive
  apt-get update
  apt-get install -y --no-install-recommends cage feh xwayland
}

# --- program + assets -------------------------------------------------------
install_files() {
  echo "==> Installing slideshow launcher and assets"
  install -D -m 0755 "$SCRIPT_DIR/bin/slideshow" /usr/local/bin/slideshow

  install -d -m 0755 "$SHARE_DIR"
  install -m 0644 "$SCRIPT_DIR/assets/black.jpg" "$SHARE_DIR/black.jpg"
  # Romanian fallback card lands here for a later slice; ship it now if present.
  [ -f "$SCRIPT_DIR/assets/fallback.png" ] && \
    install -m 0644 "$SCRIPT_DIR/assets/fallback.png" "$SHARE_DIR/fallback.png"

  # Photo source for this slice: a fixed local folder owned by the user.
  install -d -o "$FRAME_USER" -g "$FRAME_USER" -m 0755 "$FRAME_HOME/Pictures"
}

# --- runtime config ---------------------------------------------------------
install_config() {
  echo "==> Writing /etc/slideshow.conf"
  # Authoritative PHOTO_DIR for the unit's EnvironmentFile, so the slideshow
  # reads the right folder regardless of which user runs it.
  cat > /etc/slideshow.conf <<EOF
# Generated by install.sh — overrides loaded by slideshow.service.
PHOTO_DIR=$FRAME_HOME/Pictures
EOF
  chmod 0644 /etc/slideshow.conf
}

# --- systemd service --------------------------------------------------------
install_service() {
  echo "==> Installing systemd service"
  # Stamp the target user into the unit (committed unit assumes 'mihai').
  sed "s/^User=mihai$/User=$FRAME_USER/" \
    "$SCRIPT_DIR/etc/slideshow.service" > /etc/systemd/system/slideshow.service
  chmod 0644 /etc/systemd/system/slideshow.service

  systemctl daemon-reload
  systemctl enable slideshow.service
}

# --- boot config: forced display mode + quiet boot --------------------------
boot_dir() {
  if [ -d /boot/firmware ]; then echo /boot/firmware; else echo /boot; fi
}

# Keep a one-time pristine backup before we ever touch a boot file — a bad
# cmdline.txt can make the Pi unbootable.
backup_once() {
  local f="$1"
  if [ -f "$f" ] && [ ! -f "$f.frame.bak" ]; then
    cp -a "$f" "$f.frame.bak"
    echo "  backed up $f -> $f.frame.bak"
  fi
}

# Ensure a single cmdline.txt token is present (replacing any token that shares
# the same key=). cmdline.txt must stay on one line.
ensure_cmdline_token() {
  local token="$1" file="$2" key="${1%%=*}" t new=""
  local line; line="$(tr -s ' \t' ' ' < "$file" | sed 's/^ *//; s/ *$//')"
  for t in $line; do
    case "$t" in
      "$key"|"$key"=*) ;;          # drop existing token with same key
      *) new="${new:+$new }$t" ;;
    esac
  done
  new="${new:+$new }$token"
  if [ "$new" != "$line" ]; then
    printf '%s\n' "$new" > "$file"
    echo "  cmdline: set '$token'"
  else
    echo "  cmdline: '$token' already current"
  fi
}

# Ensure key=value in config.txt (replace existing/commented line, else append).
ensure_config_kv() {
  local kv="$1" file="$2" key="${1%%=*}"
  if grep -qE "^[#[:space:]]*${key}=" "$file"; then
    sed -i -E "s|^[#[:space:]]*${key}=.*|${kv}|" "$file"
  else
    printf '%s\n' "$kv" >> "$file"
  fi
  echo "  config: ensured '$kv'"
}

configure_boot() {
  local boot; boot="$(boot_dir)"
  echo "==> Configuring boot ($boot)"
  local cmdline="$boot/cmdline.txt" config="$boot/config.txt"

  if [ -f "$cmdline" ]; then
    backup_once "$cmdline"
    # Forced HDMI mode (the 'D' forces output despite a missing/late EDID),
    # plus a quiet, non-blanking console.
    ensure_cmdline_token "$FORCED_VIDEO_MODE" "$cmdline"
    ensure_cmdline_token "quiet" "$cmdline"
    ensure_cmdline_token "consoleblank=0" "$cmdline"
  else
    echo "  WARNING: $cmdline not found; skipping cmdline tweaks" >&2
  fi

  if [ -f "$config" ]; then
    backup_once "$config"
    ensure_config_kv "disable_splash=1" "$config"
  else
    echo "  WARNING: $config not found; skipping config tweaks" >&2
  fi

  # No Plymouth splash (Pi OS Lite usually has none; mask it if present).
  if systemctl cat plymouth-start.service >/dev/null 2>&1; then
    systemctl mask plymouth-start.service >/dev/null 2>&1 || true
    echo "  masked plymouth-start.service"
  fi
}

main() {
  require_root
  require_user
  install_packages
  install_files
  install_config
  install_service
  configure_boot
  echo
  echo "install: done. Reboot to start the slideshow:  sudo reboot"
}

main "$@"
