#!/bin/bash
#
# install.sh — the real installer for the digital photo frame (v2).
#
# Run as root (bootstrap.sh does this for you):  sudo ./install.sh
#
# Idempotent and re-runnable: every step is safe to apply repeatedly, so later
# slices append their own install_* function + call without breaking re-runs.
# Targets a fresh Pi OS Lite flash (Bookworm).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# The frame user (owns the slideshow session). Defaults to the user who invoked
# sudo, then to 'mihai' (the PRD's provisioned user).
FRAME_USER="${FRAME_USER:-${SUDO_USER:-mihai}}"
FRAME_HOME=""   # resolved in require_user (keeps a clean error under set -e)

SHARE_DIR="/usr/local/share/slideshow"
FORCED_VIDEO_MODE="video=HDMI-A-1:1920x1080@60D"
# Where the frame-usb helper mounts an inserted USB stick (read-only).
USB_MOUNTPOINT="/media/frame"

require_root() {
  if [ "$(id -u)" -ne 0 ]; then
    echo "install: must run as root (use: sudo ./install.sh)" >&2
    exit 1
  fi
}

require_user() {
  # getent exits non-zero for an unknown user; capturing it in the `if`
  # condition keeps set -e/pipefail from aborting before we can complain.
  if ! FRAME_HOME="$(getent passwd "$FRAME_USER" | cut -d: -f6)" || [ -z "$FRAME_HOME" ]; then
    echo "install: user '$FRAME_USER' does not exist. Set FRAME_USER=<name>." >&2
    exit 1
  fi
  echo "install: target user = $FRAME_USER ($FRAME_HOME)"
}

# --- packages ---------------------------------------------------------------
install_packages() {
  echo "==> Installing packages (cage, feh, xwayland, exfatprogs)"
  export DEBIAN_FRONTEND=noninteractive
  apt-get update
  # exfatprogs: the curated sticks are exFAT (prepared on a MacBook).
  apt-get install -y --no-install-recommends cage feh xwayland exfatprogs
}

# --- program + assets -------------------------------------------------------
install_files() {
  echo "==> Installing slideshow launcher and assets"
  install -D -m 0755 "$SCRIPT_DIR/bin/slideshow" /usr/local/bin/slideshow
  # USB mount helper run by the frame-usb-{mount,umount}@ services.
  install -D -m 0755 "$SCRIPT_DIR/bin/frame-usb" /usr/local/sbin/frame-usb

  install -d -m 0755 "$SHARE_DIR"
  # Romanian no-photos card: the slideshow's primary fallback (slice 3).
  install -m 0644 "$SCRIPT_DIR/assets/fallback.png" "$SHARE_DIR/fallback.png"
  # black.jpg is the last-resort fallback if the card is ever missing.
  install -m 0644 "$SCRIPT_DIR/assets/black.jpg" "$SHARE_DIR/black.jpg"

  # Photo source for this slice: the USB mountpoint. Create it empty so the
  # slideshow shows the fallback (not a crash) when no stick is inserted.
  install -d -m 0755 "$USB_MOUNTPOINT"
}

# --- runtime config ---------------------------------------------------------
install_config() {
  echo "==> Writing /etc/slideshow.conf"
  # Authoritative PHOTO_DIR for the unit's EnvironmentFile, so the slideshow
  # reads the right folder regardless of which user runs it.
  cat > /etc/slideshow.conf <<EOF
# Generated by install.sh — overrides loaded by slideshow.service.
PHOTO_DIR=$USB_MOUNTPOINT
EOF
  chmod 0644 /etc/slideshow.conf
}

# --- systemd service --------------------------------------------------------
install_service() {
  echo "==> Installing systemd service"
  # Stamp the target user into the unit (committed unit assumes 'mihai').
  sed "s/^User=mihai$/User=$FRAME_USER/" \
    "$SCRIPT_DIR/etc/slideshow.service" > /etc/systemd/system/slideshow.service
  chmod 0644 /etc/systemd/system/slideshow.service

  systemctl daemon-reload
  systemctl enable slideshow.service
}

# --- USB live-read: udev rule + mount/umount template services --------------
install_usb() {
  echo "==> Installing USB live-read (udev rule + mount services)"
  install -m 0644 "$SCRIPT_DIR/etc/frame-usb-mount@.service" \
    /etc/systemd/system/frame-usb-mount@.service
  install -m 0644 "$SCRIPT_DIR/etc/frame-usb-umount@.service" \
    /etc/systemd/system/frame-usb-umount@.service
  install -m 0644 "$SCRIPT_DIR/etc/99-frame-usb.rules" \
    /etc/udev/rules.d/99-frame-usb.rules

  systemctl daemon-reload
  # Reload + retrigger so a stick already inserted at install time is picked up
  # without waiting for a reboot or a re-plug.
  udevadm control --reload
  udevadm trigger --subsystem-match=block --action=add
}

# --- boot config: forced display mode + quiet boot --------------------------
boot_dir() {
  if [ -d /boot/firmware ]; then echo /boot/firmware; else echo /boot; fi
}

# Keep a one-time pristine backup before we ever touch a boot file — a bad
# cmdline.txt can make the Pi unbootable.
backup_once() {
  local f="$1"
  if [ -f "$f" ] && [ ! -f "$f.frame.bak" ]; then
    cp -a "$f" "$f.frame.bak"
    echo "  backed up $f -> $f.frame.bak"
  fi
}

# Ensure a single cmdline.txt token is present (replacing any token that shares
# the same key=). cmdline.txt must stay on one line.
ensure_cmdline_token() {
  local token="$1" file="$2" key="${1%%=*}" t new=""
  local line; line="$(tr -s ' \t' ' ' < "$file" | sed 's/^ *//; s/ *$//')"
  for t in $line; do
    case "$t" in
      "$key"|"$key"=*) ;;          # drop existing token with same key
      *) new="${new:+$new }$t" ;;
    esac
  done
  new="${new:+$new }$token"
  if [ "$new" != "$line" ]; then
    printf '%s\n' "$new" > "$file"
    echo "  cmdline: set '$token'"
  else
    echo "  cmdline: '$token' already current"
  fi
}

# Ensure key=value in config.txt (replace existing/commented line, else append).
ensure_config_kv() {
  local kv="$1" file="$2" key="${1%%=*}"
  if grep -qE "^[#[:space:]]*${key}=" "$file"; then
    sed -i -E "s|^[#[:space:]]*${key}=.*|${kv}|" "$file"
  else
    printf '%s\n' "$kv" >> "$file"
  fi
  echo "  config: ensured '$kv'"
}

configure_boot() {
  local boot; boot="$(boot_dir)"
  echo "==> Configuring boot ($boot)"
  local cmdline="$boot/cmdline.txt" config="$boot/config.txt"

  if [ -f "$cmdline" ]; then
    backup_once "$cmdline"
    # Forced HDMI mode (the 'D' forces output despite a missing/late EDID),
    # plus a quiet, non-blanking console.
    ensure_cmdline_token "$FORCED_VIDEO_MODE" "$cmdline"
    ensure_cmdline_token "quiet" "$cmdline"
    ensure_cmdline_token "consoleblank=0" "$cmdline"
  else
    echo "  WARNING: $cmdline not found; skipping cmdline tweaks" >&2
  fi

  if [ -f "$config" ]; then
    backup_once "$config"
    ensure_config_kv "disable_splash=1" "$config"
  else
    echo "  WARNING: $config not found; skipping config tweaks" >&2
  fi

  # No Plymouth splash (Pi OS Lite usually has none; mask it if present).
  if systemctl cat plymouth-start.service >/dev/null 2>&1; then
    systemctl mask plymouth-start.service >/dev/null 2>&1 || true
    echo "  masked plymouth-start.service"
  fi
}

main() {
  require_root
  require_user
  install_packages
  install_files
  install_config
  install_service
  install_usb
  configure_boot
  echo
  echo "install: done. Reboot to start the slideshow:  sudo reboot"
}

main "$@"
